#!/usr/bin/env node
/**
 * theme-guard — fails `lint` when public UI writes a colour directly instead of taking it
 * from a design token.
 *
 * The point is not to police taste. It is to keep one property true: changing the whole
 * look of the site is a value-only diff inside a single CSS file, never a find-and-replace
 * across hundreds of files that will certainly miss some.
 *
 * This guard does NOT check that you picked the *right* token — only that you did not
 * hardcode. That is why it works today, against placeholder values, before any design
 * direction is settled.
 *
 * Runtime is plain Node with no dependencies: package.json already requires Node
 * (`engines.node`), `lint` is already run through it, and a guard that needs an install
 * step is a guard that silently stops running.
 *
 * ─────────────────────────────────────────────────────────────────────────────────────
 * BLIND SPOT — read this before trusting a green run.
 *
 * A green guard is NOT evidence that a page is on-theme. It reads this project's source
 * and nothing else — it never opens `node_modules`. Any package that ships its own CSS
 * (a typography plugin, a component library, a chart library, a map library) is entirely
 * outside its field of view.
 *
 * On a previous project this guard reported zero hardcoded colours for months while every
 * rich-text surface was being painted with a typography plugin's own grey ramp. Only
 * opening the real page in both light and dark mode catches that class of drift.
 * ─────────────────────────────────────────────────────────────────────────────────────
 */

import { readdirSync, readFileSync, statSync } from 'node:fs'
import { join, relative, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

// Resolved lazily and defensively: under a test transform `import.meta.url` is not
// always a file URL, and the guard must still work when imported rather than executed.
let cachedRepoRoot = null
function repoRootDir() {
  if (cachedRepoRoot) return cachedRepoRoot
  try {
    cachedRepoRoot = join(fileURLToPath(new URL('.', import.meta.url)), '..')
  } catch {
    cachedRepoRoot = process.cwd()
  }
  return cachedRepoRoot
}

/**
 * Scan the whole source tree rather than an allow-list of UI folders.
 *
 * Listing folders is the single most dangerous constant here: the day someone adds
 * `src/sections/`, an allow-list stops seeing it and the guard reports a permanent,
 * confident "0 violations" that looks exactly like a guard that works. Scanning
 * everything and subtracting the few genuine exceptions fails in the safe direction —
 * a new folder is covered by default.
 *
 * A root may also be a single file. `tailwind.config.mjs` is one: it maps the typography
 * plugin's 36 colour variables onto tokens, so it holds real colour decisions while living
 * outside `src/`. Scanning only directories left it unguarded.
 */
const ROOTS = ['src', 'tailwind.config.mjs']

/**
 * Every entry is a hole, so each one has to earn its place.
 *
 * The design tokens govern the public site. Admin UI runs on Payload's own design system,
 * which never sees those tokens, so holding it to them would be enforcing a rule that
 * cannot be satisfied. The split is therefore by folder, and the folder is the boundary:
 * put a component in `admin/` and it is outside the token regime.
 *
 * That makes placement a real decision, not filing — sort by where a component paints,
 * not by who it serves. AdminBar is editor tooling but renders on public pages, so it
 * lives under `public/` and stays covered.
 */
const EXCLUDE = [
  // The one legal home for colour. Excluding it is the entire premise of the guard.
  'src/app/(frontend)/globals.css',
  // The CMS admin panel: generated route files that say "DO NOT MODIFY", rendered by
  // Payload's own design system, which never sees the frontend tokens.
  'src/app/(payload)/',
  // Admin UI that lives outside the route group: same design system, same reasoning.
  'src/components/admin/',
  // Generated by `payload generate:types`; rewritten wholesale, so a hit is unfixable.
  'src/payload-types.ts',
]

const EXTENSIONS = new Set(['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs', '.css', '.scss'])
const SKIP_DIRS = new Set(['node_modules', '.next', '.git', 'dist', 'build', 'coverage'])

const IGNORE_MARKER = 'theme-guard-ignore'
const TOKEN_FILE = 'src/app/(frontend)/globals.css'

const COLOUR_FAMILIES =
  'slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose'
const UTILITY_PREFIXES =
  'bg|text|border|ring|fill|stroke|from|via|to|outline|divide|decoration|accent|caret'

/**
 * Exactly three checks. Each extra check is another source of false positives, and false
 * positives kill a guard far faster than false negatives — one bad failure and someone
 * adds an exclusion, or deletes the whole thing.
 */
const CHECKS = [
  {
    name: 'raw-colour-fn',
    // A colour function called with literal channel values instead of a token.
    re: new RegExp(String.raw`\b(?:rgba?|hsla?|oklch|lab|lch)\s*\(`, 'g'),
  },
  {
    name: 'tailwind-palette',
    // The most common way UI drifts off-theme: `text-gray-500` instead of
    // `text-muted-foreground`. It *looks* like a token, so it sails through review.
    re: new RegExp(String.raw`\b(?:${UTILITY_PREFIXES})-(?:${COLOUR_FAMILIES})-\d{1,3}\b`, 'g'),
  },
]

/**
 * Blank out comment text while keeping every other character, and every newline, at its
 * original offset — so a violation still reports the line it is actually on.
 *
 * This exists because `#` followed by three hex digits is also how people write an issue
 * number. `(#104)` in prose is indistinguishable from the colour `#104`. On a previous
 * project that hard-failed `lint` on the very convention that project's own docs asked
 * for. Prose is not shipped style; what this guard protects is code.
 *
 * Quotes are tracked for exactly one reason: `//` inside a string does not open a comment
 * (`https://…`, a base64 data URI). Miss that and the guard goes blind for the rest of
 * the line. String *contents* are still scanned — a colour in a string is still a colour.
 * The reverse holds too: inside a comment a quote is just prose, so a lone apostrophe in
 * English JSDoc ("don't") must not swallow the rest of the file.
 *
 * Regex literals are deliberately not parsed. Telling a division `/` from a regex-opening
 * `/` needs a real parser. The only failure that matters is reading *code* as a *comment*,
 * which needs an unescaped `//` or `/*` inside a regex — rare, and far cheaper than
 * shipping a JS parser.
 */
function stripComments(src, { lineComments, quotes }) {
  const out = new Array(src.length)
  const n = src.length
  let state = 'code'
  let quote = ''
  let i = 0

  while (i < n) {
    const c = src[i]
    const c2 = i + 1 < n ? src[i + 1] : ''

    if (state === 'code') {
      if (lineComments && c === '/' && c2 === '/') {
        state = 'line'
        out[i] = ' '
        out[i + 1] = ' '
        i += 2
        continue
      }
      if (c === '/' && c2 === '*') {
        state = 'block'
        out[i] = ' '
        out[i + 1] = ' '
        i += 2
        continue
      }
      if (quotes.includes(c)) {
        state = 'string'
        quote = c
      }
      out[i] = c
      i += 1
      continue
    }

    if (state === 'string') {
      if (c === '\\') {
        out[i] = c
        if (i + 1 < n) out[i + 1] = src[i + 1]
        i += 2
        continue
      }
      if (c === quote) state = 'code'
      // An unterminated '…' or "…" cannot span lines; a template literal can.
      else if (c === '\n' && quote !== '`') state = 'code'
      out[i] = c
      i += 1
      continue
    }

    if (state === 'line') {
      if (c === '\n') {
        state = 'code'
        out[i] = c
      } else {
        out[i] = ' '
      }
      i += 1
      continue
    }

    // block comment
    if (c === '*' && c2 === '/') {
      state = 'code'
      out[i] = ' '
      out[i + 1] = ' '
      i += 2
      continue
    }
    out[i] = c === '\n' ? '\n' : ' '
    i += 1
  }

  return out.join('')
}

/**
 * Hex colours are 3, 4, 6 or 8 digits. Matching the whole run and then filtering by
 * length keeps `#12345` and `#abcdefgh` from being read as a shorter colour.
 */
function findHex(line) {
  const hits = []
  const re = /#([0-9a-fA-F]+)(?![\w-])/g
  let m
  while ((m = re.exec(line)) !== null) {
    const len = m[1].length
    if (len === 3 || len === 4 || len === 6 || len === 8) hits.push(m[0])
  }
  return hits
}

export function isExcluded(relPath) {
  const p = relPath.split(sep).join('/')
  return EXCLUDE.some((entry) => (entry.endsWith('/') ? p.startsWith(entry) : p === entry))
}

function collectFiles(dir, acc) {
  let entries
  try {
    entries = readdirSync(dir, { withFileTypes: true })
  } catch {
    return acc
  }
  for (const entry of entries) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue
      collectFiles(full, acc)
      continue
    }
    if (!entry.isFile()) continue
    const dot = entry.name.lastIndexOf('.')
    if (dot < 0 || !EXTENSIONS.has(entry.name.slice(dot))) continue
    const rel = relative(repoRootDir(), full)
    if (isExcluded(rel)) continue
    acc.push({ full, rel: rel.split(sep).join('/') })
  }
  return acc
}

/** Pure core: given a repo-relative path and its source, list the violations. */
export function scanSource(relPath, src) {
  const isCss = relPath.endsWith('.css')
  const isStyle = isCss || relPath.endsWith('.scss')
  const stripped = stripComments(src, {
    // Plain CSS has no `//` comment — treating one as a comment would blind the guard
    // to everything after a `url(https://…)`. SCSS does have `//`.
    lineComments: !isCss,
    quotes: isStyle ? ['"', "'"] : ['"', "'", '`'],
  })

  const rawLines = src.split(/\r?\n/)
  const lines = stripped.split(/\r?\n/)
  const violations = []

  lines.forEach((line, index) => {
    const raw = rawLines[index] ?? ''
    if (raw.includes(IGNORE_MARKER)) return

    const found = [
      ...findHex(line).map((text) => ({ name: 'hex-colour', text })),
      ...CHECKS.flatMap((check) => {
        check.re.lastIndex = 0
        return (line.match(check.re) ?? []).map((text) => ({ name: check.name, text }))
      }),
    ]

    for (const hit of found) {
      violations.push({ file: relPath, line: index + 1, ...hit })
    }
  })

  return violations
}

function scanFile(file) {
  try {
    return scanSource(file.rel, readFileSync(file.full, 'utf8'))
  } catch {
    return []
  }
}

export function main() {
  const files = []
  for (const root of ROOTS) {
    const full = join(repoRootDir(), root)
    try {
      if (statSync(full).isDirectory()) collectFiles(full, files)
      // A file named directly was chosen on purpose, so it skips the extension filter —
      // but silently collecting nothing here would be the "0 violations" lie again.
      else files.push({ full, rel: root })
    } catch {
      // A root that does not exist is a configuration error worth shouting about.
      process.stderr.write(`theme-guard: ROOTS entry not found: ${root}\n`)
      process.exit(2)
    }
  }

  if (files.length === 0) {
    // Zero files scanned is the failure that looks exactly like success. Never pass here.
    process.stderr.write(`theme-guard: scanned 0 files — check ROOTS/EXTENSIONS.\n`)
    process.exit(2)
  }

  const violations = files.flatMap(scanFile)

  if (violations.length === 0) {
    process.stdout.write(`✓ theme-guard: 0 violations across ${files.length} files\n`)
    return
  }

  const width = Math.max(...violations.map((v) => v.name.length))
  process.stderr.write('\ntheme-guard: hardcoded colour in public UI\n\n')
  for (const v of violations) {
    process.stderr.write(`  ${v.file}:${v.line}  ${v.name.padEnd(width)}  ${v.text}\n`)
  }
  process.stderr.write(`\n${violations.length} violation(s) across ${files.length} files.\n`)
  process.stderr.write(
    `Take the colour from a token instead. Need a new colour role? Add it to\n` +
      `${TOKEN_FILE} — do not inline it here.\n` +
      `A genuinely unavoidable colour (a third-party brand, say) can carry\n` +
      `\`${IGNORE_MARKER}\` in a comment on that line.\n`,
  )
  process.exit(1)
}

// Only run when invoked directly, so tests can import the pure parts above.
function invokedDirectly() {
  try {
    return Boolean(process.argv[1]) && resolve(process.argv[1]) === fileURLToPath(import.meta.url)
  } catch {
    return false
  }
}

if (invokedDirectly()) {
  main()
}
